---
version: "3.8"
services:
  movies:
    image: biroue/movies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3

  train:
    image: biroue/train:latest
    ports:
      - 82:80
    deploy:
      replicas: 3

  dth:
    image: biroue/dth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3

  recharge:
    image: biroue/recharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
