---
version: "3.8"
services:
  movies:
    image: biroue/paymovies:latest
    ports:
      - 81:80
    deploy:
      replicas: 3

  train:
    image: biroue/paytrain:latest
    ports:
      - 82:80
    deploy:
      replicas: 3

  dth:
    image: biroue/paydth:latest
    ports:
      - 83:80
    deploy:
      replicas: 3

  recharge:
    image: biroue/payrecharge:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
